# This file was generated

attributes = {
    1150000: {
        "name": "INTERFACE_NUMBER",
        "full_name": "NISYNC_ATTR_INTERFACE_NUMBER",
        "short_name": "INTERFACE_NUMBER",
        "long_name": "NISYNC_ATTR_INTF_NUM",
        "namespace": "Session",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150001: {
        "name": "SERIAL_NUMBER",
        "full_name": "NISYNC_ATTR_SERIAL_NUMBER",
        "short_name": "SERIAL_NUMBER",
        "long_name": "NISYNC_ATTR_SERIAL_NUM",
        "namespace": "Session",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150100: {
        "name": "PFI0_THRESHOLD",
        "full_name": "NISYNC_ATTR_PFI0_THRESHOLD",
        "short_name": "PFI0_THRESHOLD",
        "long_name": "NISYNC_ATTR_PFI0_THRESHOLD",
        "namespace": "Session",
        "type": "ViReal64",
        "visibility": "public",
    },
    1150101: {
        "name": "PFI1_THRESHOLD",
        "full_name": "NISYNC_ATTR_PFI1_THRESHOLD",
        "short_name": "PFI1_THRESHOLD",
        "long_name": "NISYNC_ATTR_PFI1_THRESHOLD",
        "namespace": "Session",
        "type": "ViReal64",
        "visibility": "public",
    },
    1150102: {
        "name": "PFI2_THRESHOLD",
        "full_name": "NISYNC_ATTR_PFI2_THRESHOLD",
        "short_name": "PFI2_THRESHOLD",
        "long_name": "NISYNC_ATTR_PFI2_THRESHOLD",
        "namespace": "Session",
        "type": "ViReal64",
        "visibility": "public",
    },
    1150103: {
        "name": "PFI3_THRESHOLD",
        "full_name": "NISYNC_ATTR_PFI3_THRESHOLD",
        "short_name": "PFI3_THRESHOLD",
        "long_name": "NISYNC_ATTR_PFI3_THRESHOLD",
        "namespace": "Session",
        "type": "ViReal64",
        "visibility": "public",
    },
    1150104: {
        "name": "PFI4_THRESHOLD",
        "full_name": "NISYNC_ATTR_PFI4_THRESHOLD",
        "short_name": "PFI4_THRESHOLD",
        "long_name": "NISYNC_ATTR_PFI4_THRESHOLD",
        "namespace": "Session",
        "type": "ViReal64",
        "visibility": "public",
    },
    1150105: {
        "name": "PFI5_THRESHOLD",
        "full_name": "NISYNC_ATTR_PFI5_THRESHOLD",
        "short_name": "PFI5_THRESHOLD",
        "long_name": "NISYNC_ATTR_PFI5_THRESHOLD",
        "namespace": "Session",
        "type": "ViReal64",
        "visibility": "public",
    },
    1150106: {
        "name": "OSCILLATOR_VOLTAGE",
        "full_name": "NISYNC_ATTR_OSCILLATOR_VOLTAGE",
        "short_name": "OSCILLATOR_VOLTAGE",
        "long_name": "NISYNC_ATTR_OSCILLATOR_VOLTAGE",
        "namespace": "Session",
        "type": "ViReal64",
        "visibility": "public",
    },
    1150107: {
        "name": "CLK10_PHASE_ADJUST",
        "full_name": "NISYNC_ATTR_CLK10_PHASE_ADJUST",
        "short_name": "CLK10_PHASE_ADJUST",
        "long_name": "NISYNC_ATTR_CLK10_PHASE_ADJUST",
        "namespace": "Session",
        "type": "ViReal64",
        "visibility": "public",
    },
    1150108: {
        "name": "DDS_VCXO_VOLTAGE",
        "full_name": "NISYNC_ATTR_DDS_VCXO_VOLTAGE",
        "short_name": "DDS_VCXO_VOLTAGE",
        "long_name": "NISYNC_ATTR_DDS_VCXO_VOLTAGE",
        "namespace": "Session",
        "type": "ViReal64",
        "visibility": "public",
    },
    1150109: {
        "name": "DDS_PHASE_ADJUST",
        "full_name": "NISYNC_ATTR_DDS_PHASE_ADJUST",
        "short_name": "DDS_PHASE_ADJUST",
        "long_name": "NISYNC_ATTR_DDS_PHASE_ADJUST",
        "namespace": "Session",
        "type": "ViReal64",
        "visibility": "public",
    },
    1150110: {
        "name": "PFI0_1KOHM_ENABLE",
        "full_name": "NISYNC_ATTR_PFI0_1KOHM_ENABLE",
        "short_name": "PFI0_1KOHM_ENABLE",
        "long_name": "NISYNC_ATTR_PFI0_1KOHM_ENABLE",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150111: {
        "name": "PFI1_1KOHM_ENABLE",
        "full_name": "NISYNC_ATTR_PFI1_1KOHM_ENABLE",
        "short_name": "PFI1_1KOHM_ENABLE",
        "long_name": "NISYNC_ATTR_PFI1_1KOHM_ENABLE",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150112: {
        "name": "PFI2_1KOHM_ENABLE",
        "full_name": "NISYNC_ATTR_PFI2_1KOHM_ENABLE",
        "short_name": "PFI2_1KOHM_ENABLE",
        "long_name": "NISYNC_ATTR_PFI2_1KOHM_ENABLE",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150113: {
        "name": "PFI3_1KOHM_ENABLE",
        "full_name": "NISYNC_ATTR_PFI3_1KOHM_ENABLE",
        "short_name": "PFI3_1KOHM_ENABLE",
        "long_name": "NISYNC_ATTR_PFI3_1KOHM_ENABLE",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150114: {
        "name": "PFI4_1KOHM_ENABLE",
        "full_name": "NISYNC_ATTR_PFI4_1KOHM_ENABLE",
        "short_name": "PFI4_1KOHM_ENABLE",
        "long_name": "NISYNC_ATTR_PFI4_1KOHM_ENABLE",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150115: {
        "name": "PFI5_1KOHM_ENABLE",
        "full_name": "NISYNC_ATTR_PFI5_1KOHM_ENABLE",
        "short_name": "PFI5_1KOHM_ENABLE",
        "long_name": "NISYNC_ATTR_PFI5_1KOHM_ENABLE",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150116: {
        "name": "PFI0_10KOHM_ENABLE",
        "full_name": "NISYNC_ATTR_PFI0_10KOHM_ENABLE",
        "short_name": "PFI0_10KOHM_ENABLE",
        "long_name": "NISYNC_ATTR_PFI0_10KOHM_ENABLE",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150117: {
        "name": "PFI1_10KOHM_ENABLE",
        "full_name": "NISYNC_ATTR_PFI1_10KOHM_ENABLE",
        "short_name": "PFI1_10KOHM_ENABLE",
        "long_name": "NISYNC_ATTR_PFI1_10KOHM_ENABLE",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150118: {
        "name": "PFI2_10KOHM_ENABLE",
        "full_name": "NISYNC_ATTR_PFI2_10KOHM_ENABLE",
        "short_name": "PFI2_10KOHM_ENABLE",
        "long_name": "NISYNC_ATTR_PFI2_10KOHM_ENABLE",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150119: {
        "name": "PFI3_10KOHM_ENABLE",
        "full_name": "NISYNC_ATTR_PFI3_10KOHM_ENABLE",
        "short_name": "PFI3_10KOHM_ENABLE",
        "long_name": "NISYNC_ATTR_PFI3_10KOHM_ENABLE",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150120: {
        "name": "PFI4_10KOHM_ENABLE",
        "full_name": "NISYNC_ATTR_PFI4_10KOHM_ENABLE",
        "short_name": "PFI4_10KOHM_ENABLE",
        "long_name": "NISYNC_ATTR_PFI4_10KOHM_ENABLE",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150121: {
        "name": "PFI5_10KOHM_ENABLE",
        "full_name": "NISYNC_ATTR_PFI5_10KOHM_ENABLE",
        "short_name": "PFI5_10KOHM_ENABLE",
        "long_name": "NISYNC_ATTR_PFI5_10KOHM_ENABLE",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150200: {
        "name": "FRONT_SYNC_CLK_SRC",
        "full_name": "NISYNC_ATTR_FRONT_SYNC_CLK_SRC",
        "short_name": "FRONT_SYNC_CLK_SRC",
        "long_name": "NISYNC_ATTR_FRONT_SYNC_CLK_SRC",
        "namespace": "Session",
        "type": "ViString",
        "visibility": "public",
    },
    1150201: {
        "name": "REAR_SYNC_CLK_SRC",
        "full_name": "NISYNC_ATTR_REAR_SYNC_CLK_SRC",
        "short_name": "REAR_SYNC_CLK_SRC",
        "long_name": "NISYNC_ATTR_REAR_SYNC_CLK_SRC",
        "namespace": "Session",
        "type": "ViString",
        "visibility": "public",
    },
    1150202: {
        "name": "SYNC_CLK_DIV1",
        "full_name": "NISYNC_ATTR_SYNC_CLK_DIV1",
        "short_name": "SYNC_CLK_DIV1",
        "long_name": "NISYNC_ATTR_SYNC_CLK_DIV1",
        "namespace": "Session",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150203: {
        "name": "SYNC_CLK_DIV2",
        "full_name": "NISYNC_ATTR_SYNC_CLK_DIV2",
        "short_name": "SYNC_CLK_DIV2",
        "long_name": "NISYNC_ATTR_SYNC_CLK_DIV2",
        "namespace": "Session",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150204: {
        "name": "SYNC_CLK_RST_PXITRIG_NUM",
        "full_name": "NISYNC_ATTR_SYNC_CLK_RST_PXITRIG_NUM",
        "short_name": "SYNC_CLK_RST_PXITRIG_NUM",
        "long_name": "NISYNC_ATTR_SYNC_CLK_RST_PXITRIG_NUM",
        "namespace": "Session",
        "type": "ViString",
        "visibility": "public",
    },
    1150205: {
        "name": "SYNC_CLK_PFI0_FREQ",
        "full_name": "NISYNC_ATTR_SYNC_CLK_PFI0_FREQ",
        "short_name": "SYNC_CLK_PFI0_FREQ",
        "long_name": "NISYNC_ATTR_SYNC_CLK_PFI0_FREQ",
        "namespace": "Session",
        "type": "ViReal64",
        "visibility": "public",
    },
    1150206: {
        "name": "SYNC_CLK_RST_DDS_CNTR_ON_PXITRIG",
        "full_name": "NISYNC_ATTR_SYNC_CLK_RST_DDS_CNTR_ON_PXITRIG",
        "short_name": "SYNC_CLK_RST_DDS_CNTR_ON_PXITRIG",
        "long_name": "NISYNC_ATTR_SYNC_CLK_RST_DDS_CNTR_ON_PXITRIG",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150207: {
        "name": "SYNC_CLK_RST_PFI0_CNTR_ON_PXITRIG",
        "full_name": "NISYNC_ATTR_SYNC_CLK_RST_PFI0_CNTR_ON_PXITRIG",
        "short_name": "SYNC_CLK_RST_PFI0_CNTR_ON_PXITRIG",
        "long_name": "NISYNC_ATTR_SYNC_CLK_RST_PFI0_CNTR_ON_PXITRIG",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150208: {
        "name": "SYNC_CLK_RST_CLK10_CNTR_ON_PXITRIG",
        "full_name": "NISYNC_ATTR_SYNC_CLK_RST_CLK10_CNTR_ON_PXITRIG",
        "short_name": "SYNC_CLK_RST_CLK10_CNTR_ON_PXITRIG",
        "long_name": "NISYNC_ATTR_SYNC_CLK_RST_CLK10_CNTR_ON_PXITRIG",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150300: {
        "name": "TERMINAL_STATE_PXISTAR",
        "full_name": "NISYNC_ATTR_TERMINAL_STATE_PXISTAR",
        "short_name": "TERMINAL_STATE_PXISTAR",
        "long_name": "NISYNC_ATTR_TERMINAL_STATE_PXISTAR",
        "namespace": "Session",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150301: {
        "name": "TERMINAL_STATE_PXITRIG",
        "full_name": "NISYNC_ATTR_TERMINAL_STATE_PXITRIG",
        "short_name": "TERMINAL_STATE_PXITRIG",
        "long_name": "NISYNC_ATTR_TERMINAL_STATE_PXITRIG",
        "namespace": "Session",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150302: {
        "name": "TERMINAL_STATE_PFI",
        "full_name": "NISYNC_ATTR_TERMINAL_STATE_PFI",
        "short_name": "TERMINAL_STATE_PFI",
        "long_name": "NISYNC_ATTR_TERMINAL_STATE_PFI",
        "namespace": "Session",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150303: {
        "name": "TERMINAL_STATE_PXIEDSTARC",
        "full_name": "NISYNC_ATTR_TERMINAL_STATE_PXIEDSTARC",
        "short_name": "TERMINAL_STATE_PXIEDSTARC",
        "long_name": "NISYNC_ATTR_TERMINAL_STATE_PXIEDSTARC",
        "namespace": "Session",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150304: {
        "name": "TERMINAL_STATE_PFILVDS",
        "full_name": "NISYNC_ATTR_TERMINAL_STATE_PFILVDS",
        "short_name": "TERMINAL_STATE_PFILVDS",
        "long_name": "NISYNC_ATTR_TERMINAL_STATE_PFILVDS",
        "namespace": "Session",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150305: {
        "name": "TERMINAL_STATE_PXIEDSTARCPERIPHERAL",
        "full_name": "NISYNC_ATTR_TERMINAL_STATE_PXIEDSTARCPERIPHERAL",
        "short_name": "TERMINAL_STATE_PXIEDSTARCPERIPHERAL",
        "long_name": "NISYNC_ATTR_TERMINAL_STATE_PXIEDSTARCPERIPHERAL",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150306: {
        "name": "TERMINAL_STATE_PXIEDSTARBPERIPHERAL",
        "full_name": "NISYNC_ATTR_TERMINAL_STATE_PXIEDSTARBPERIPHERAL",
        "short_name": "TERMINAL_STATE_PXIEDSTARBPERIPHERAL",
        "long_name": "NISYNC_ATTR_TERMINAL_STATE_PXIEDSTARBPERIPHERAL",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150307: {
        "name": "TERMINAL_STATE_PXISTARPERIPHERAL",
        "full_name": "NISYNC_ATTR_TERMINAL_STATE_PXISTARPERIPHERAL",
        "short_name": "TERMINAL_STATE_PXISTARPERIPHERAL",
        "long_name": "NISYNC_ATTR_TERMINAL_STATE_PXISTARPERIPHERAL",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150400: {
        "name": "DDS_FREQUENCY",
        "full_name": "NISYNC_ATTR_DDS_FREQUENCY",
        "short_name": "DDS_FREQUENCY",
        "long_name": "NISYNC_ATTR_DDS_FREQ",
        "namespace": "Session",
        "type": "ViReal64",
        "visibility": "public",
    },
    1150401: {
        "name": "DDS_UPDATE_SOURCE",
        "full_name": "NISYNC_ATTR_DDS_UPDATE_SOURCE",
        "short_name": "DDS_UPDATE_SOURCE",
        "long_name": "NISYNC_ATTR_DDS_UPDATE_SOURCE",
        "namespace": "Session",
        "type": "ViString",
        "visibility": "public",
    },
    1150402: {
        "name": "DDS_INITIAL_DELAY",
        "full_name": "NISYNC_ATTR_DDS_INITIAL_DELAY",
        "short_name": "DDS_INITIAL_DELAY",
        "long_name": "NISYNC_ATTR_DDS_INITIAL_DELAY",
        "namespace": "Session",
        "type": "ViReal64",
        "visibility": "public",
    },
    1150500: {
        "name": "CLKIN_PLL_FREQ",
        "full_name": "NISYNC_ATTR_CLKIN_PLL_FREQ",
        "short_name": "CLKIN_PLL_FREQ",
        "long_name": "NISYNC_ATTR_CLKIN_PLL_FREQ",
        "namespace": "Session",
        "type": "ViReal64",
        "visibility": "public",
    },
    1150501: {
        "name": "CLKIN_USE_PLL",
        "full_name": "NISYNC_ATTR_CLKIN_USE_PLL",
        "short_name": "CLKIN_USE_PLL",
        "long_name": "NISYNC_ATTR_CLKIN_USE_PLL",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150502: {
        "name": "CLKIN_PLL_LOCKED",
        "full_name": "NISYNC_ATTR_CLKIN_PLL_LOCKED",
        "short_name": "CLKIN_PLL_LOCKED",
        "long_name": "NISYNC_ATTR_CLKIN_PLL_LOCKED",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150503: {
        "name": "CLKOUT_GAIN_ENABLE",
        "full_name": "NISYNC_ATTR_CLKOUT_GAIN_ENABLE",
        "short_name": "CLKOUT_GAIN_ENABLE",
        "long_name": "NISYNC_ATTR_CLKOUT_GAIN_ENABLE",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150504: {
        "name": "PXICLK10_PRESENT",
        "full_name": "NISYNC_ATTR_PXICLK10_PRESENT",
        "short_name": "PXICLK10_PRESENT",
        "long_name": "NISYNC_ATTR_PXICLK10_PRESENT",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150505: {
        "name": "CLKIN_ATTENUATION_DISABLE",
        "full_name": "NISYNC_ATTR_CLKIN_ATTENUATION_DISABLE",
        "short_name": "CLKIN_ATTENUATION_DISABLE",
        "long_name": "NISYNC_ATTR_CLKIN_ATTENUATION_DISABLE",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150600: {
        "name": "USER_LED_STATE",
        "full_name": "NISYNC_ATTR_USER_LED_STATE",
        "short_name": "USER_LED_STATE",
        "long_name": "NISYNC_ATTR_USER_LED_STATE",
        "namespace": "Session",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150700: {
        "name": "IEEE_1588_IP_ADDRESS",
        "full_name": "NISYNC_ATTR_1588_IP_ADDRESS",
        "short_name": "IP_ADDRESS",
        "long_name": "NISYNC_ATTR_1588_IP_ADDRESS",
        "namespace": "IEEE1588TimeReference",
        "type": "ViString",
        "visibility": "public",
    },
    1150712: {
        "name": "IEEE_1588_PORT_STATE",
        "full_name": "NISYNC_ATTR_1588_PORT_STATE",
        "short_name": "PORT_STATE",
        "long_name": "NISYNC_ATTR_1588_PORT_STATE",
        "namespace": "IEEE1588Port",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150718: {
        "name": "TIMESTAMP_BUFFER_SIZE",
        "full_name": "NISYNC_ATTR_1588_TIMESTAMP_BUFFER_SIZE",
        "short_name": "TIMESTAMP_BUFFER_SIZE",
        "long_name": "NISYNC_ATTR_1588_TIMESTAMP_BUF_SIZE",
        "namespace": "Session",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150719: {
        "name": "AVAILABLE_TIMESTAMPS",
        "full_name": "NISYNC_ATTR_1588_AVAILABLE_TIMESTAMPS",
        "short_name": "AVAILABLE_TIMESTAMPS",
        "long_name": "NISYNC_ATTR_1588_AVAIL_TIMESTAMPS",
        "namespace": "Session",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150720: {
        "name": "CLOCK_RESOLUTION",
        "full_name": "NISYNC_ATTR_1588_CLOCK_RESOLUTION",
        "short_name": "CLOCK_RESOLUTION",
        "long_name": "NISYNC_ATTR_1588_CLK_RESOLUTION",
        "namespace": "Session",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150729: {
        "name": "IEEE_1588_CLOCK_ID",
        "full_name": "NISYNC_ATTR_1588_CLOCK_ID",
        "short_name": "CLOCK_ID",
        "long_name": "NISYNC_ATTR_1588_CLOCK_ID",
        "namespace": "IEEE1588TimeReference",
        "type": "ViString",
        "visibility": "public",
    },
    1150730: {
        "name": "IEEE_1588_CLOCK_CLASS",
        "full_name": "NISYNC_ATTR_1588_CLOCK_CLASS",
        "short_name": "CLOCK_CLASS",
        "long_name": "NISYNC_ATTR_1588_CLOCK_CLASS",
        "namespace": "IEEE1588TimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150731: {
        "name": "IEEE_1588_CLOCK_ACCURACY",
        "full_name": "NISYNC_ATTR_1588_CLOCK_ACCURACY",
        "short_name": "CLOCK_ACCURACY",
        "long_name": "NISYNC_ATTR_1588_CLOCK_ACCURACY",
        "namespace": "IEEE1588TimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150732: {
        "name": "IEEE_1588_PRIORITY1",
        "full_name": "NISYNC_ATTR_1588_PRIORITY1",
        "short_name": "PRIORITY1",
        "long_name": "NISYNC_ATTR_1588_PRIORITY1",
        "namespace": "IEEE1588TimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150733: {
        "name": "IEEE_1588_PRIORITY2",
        "full_name": "NISYNC_ATTR_1588_PRIORITY2",
        "short_name": "PRIORITY2",
        "long_name": "NISYNC_ATTR_1588_PRIORITY2",
        "namespace": "IEEE1588TimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150734: {
        "name": "IEEE_1588_GRANDMASTER_CLOCK_ID",
        "full_name": "NISYNC_ATTR_1588_GRANDMASTER_CLOCK_ID",
        "short_name": "GRANDMASTER_CLOCK_ID",
        "long_name": "NISYNC_ATTR_1588_GRANDMASTER_CLOCK_ID",
        "namespace": "IEEE1588TimeReference",
        "type": "ViString",
        "visibility": "public",
    },
    1150735: {
        "name": "IEEE_1588_GRANDMASTER_CLOCK_CLASS",
        "full_name": "NISYNC_ATTR_1588_GRANDMASTER_CLOCK_CLASS",
        "short_name": "GRANDMASTER_CLOCK_CLASS",
        "long_name": "NISYNC_ATTR_1588_GRANDMASTER_CLOCK_CLASS",
        "namespace": "IEEE1588TimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150736: {
        "name": "IEEE_1588_GRANDMASTER_CLOCK_ACCURACY",
        "full_name": "NISYNC_ATTR_1588_GRANDMASTER_CLOCK_ACCURACY",
        "short_name": "GRANDMASTER_CLOCK_ACCURACY",
        "long_name": "NISYNC_ATTR_1588_GRANDMASTER_CLOCK_ACCURACY",
        "namespace": "IEEE1588TimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150737: {
        "name": "IEEE_1588_GRANDMASTER_PRIORITY1",
        "full_name": "NISYNC_ATTR_1588_GRANDMASTER_PRIORITY1",
        "short_name": "GRANDMASTER_PRIORITY1",
        "long_name": "NISYNC_ATTR_1588_GRANDMASTER_PRIORITY1",
        "namespace": "IEEE1588TimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150738: {
        "name": "IEEE_1588_GRANDMASTER_PRIORITY2",
        "full_name": "NISYNC_ATTR_1588_GRANDMASTER_PRIORITY2",
        "short_name": "GRANDMASTER_PRIORITY2",
        "long_name": "NISYNC_ATTR_1588_GRANDMASTER_PRIORITY2",
        "namespace": "IEEE1588TimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150716: {
        "name": "IEEE_1588_STEPS_TO_GRANDMASTER",
        "full_name": "NISYNC_ATTR_1588_STEPS_TO_GRANDMASTER",
        "short_name": "STEPS_TO_GRANDMASTER",
        "long_name": "NISYNC_ATTR_1588_STEPS_TO_GRANDMASTER",
        "namespace": "IEEE1588TimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150739: {
        "name": "IEEE_1588_LOG_SYNC_INTERVAL",
        "full_name": "NISYNC_ATTR_1588_LOG_SYNC_INTERVAL",
        "short_name": "LOG_SYNC_INTERVAL",
        "long_name": "NISYNC_ATTR_1588_LOG_SYNC_INTERVAL",
        "namespace": "IEEE1588Port",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150740: {
        "name": "IEEE_1588_MEAN_PATH_DELAY",
        "full_name": "NISYNC_ATTR_1588_MEAN_PATH_DELAY",
        "short_name": "MEAN_PATH_DELAY",
        "long_name": "NISYNC_ATTR_1588_MEAN_PATH_DELAY",
        "namespace": "IEEE1588TimeReference",
        "type": "ViReal64",
        "visibility": "public",
    },
    1150741: {
        "name": "IEEE_1588_GRANDMASTER_IP_ADDRESS",
        "full_name": "NISYNC_ATTR_1588_GRANDMASTER_IP_ADDRESS",
        "short_name": "GRANDMASTER_IP_ADDRESS",
        "long_name": "NISYNC_ATTR_1588_GRANDMASTER_IP_ADDRESS",
        "namespace": "IEEE1588TimeReference",
        "type": "ViString",
        "visibility": "public",
    },
    1150742: {
        "name": "IEEE_1588_BMCA_MODE",
        "full_name": "NISYNC_ATTR_1588_BMCA_MODE",
        "short_name": "BMCA_MODE",
        "long_name": "NISYNC_ATTR_1588_BMCA_MODE",
        "namespace": "IEEE1588TimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150743: {
        "name": "IEEE_1588_INTERFACE_NAME",
        "full_name": "NISYNC_ATTR_1588_INTERFACE_NAME",
        "short_name": "INTERFACE_NAME",
        "long_name": "NISYNC_ATTR_1588_INTERFACE_NAME",
        "namespace": "IEEE1588Port",
        "type": "ViString",
        "visibility": "public",
    },
    1150752: {
        "name": "IEEE_1588_OFFSET_SCALED_LOG_VARIANCE",
        "full_name": "NISYNC_ATTR_1588_OFFSET_SCALED_LOG_VARIANCE",
        "short_name": "OFFSET_SCALED_LOG_VARIANCE",
        "long_name": "NISYNC_ATTR_1588_OFFSET_SCALED_LOG_VARIANCE",
        "namespace": "IEEE1588TimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150763: {
        "name": "IEEE_1588_LEAP59",
        "full_name": "NISYNC_ATTR_1588_LEAP59",
        "short_name": "LEAP59",
        "long_name": "NISYNC_ATTR_1588_LEAP59",
        "namespace": "IEEE1588TimeReference",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150764: {
        "name": "IEEE_1588_LEAP61",
        "full_name": "NISYNC_ATTR_1588_LEAP61",
        "short_name": "LEAP61",
        "long_name": "NISYNC_ATTR_1588_LEAP61",
        "namespace": "IEEE1588TimeReference",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150765: {
        "name": "IEEE_1588_TIME_TRACEABLE",
        "full_name": "NISYNC_ATTR_1588_TIME_TRACEABLE",
        "short_name": "TIME_TRACEABLE",
        "long_name": "NISYNC_ATTR_1588_TIME_TRACEABLE",
        "namespace": "IEEE1588TimeReference",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150766: {
        "name": "IEEE_1588_FREQUENCY_TRACEABLE",
        "full_name": "NISYNC_ATTR_1588_FREQUENCY_TRACEABLE",
        "short_name": "FREQUENCY_TRACEABLE",
        "long_name": "NISYNC_ATTR_1588_FREQUENCY_TRACEABLE",
        "namespace": "IEEE1588TimeReference",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150768: {
        "name": "IEEE_1588_TIME_SOURCE",
        "full_name": "NISYNC_ATTR_1588_TIME_SOURCE",
        "short_name": "TIME_SOURCE",
        "long_name": "NISYNC_ATTR_1588_TIME_SOURCE",
        "namespace": "IEEE1588TimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150800: {
        "name": "TIME_REFERENCE_PRESENT",
        "full_name": "NISYNC_ATTR_TIMEREF_PRESENT",
        "short_name": "PRESENT",
        "long_name": "NISYNC_ATTR_TIMEREF_PRESENT",
        "namespace": "TimeReference",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150802: {
        "name": "TIME_REFERENCE_OFFSET",
        "full_name": "NISYNC_ATTR_TIMEREF_OFFSET",
        "short_name": "OFFSET",
        "long_name": "NISYNC_ATTR_TIMEREF_OFFSET",
        "namespace": "TimeReference",
        "type": "ViReal64",
        "visibility": "public",
    },
    1150808: {
        "name": "TIME_REFERENCE_OFFSET_NS",
        "full_name": "NISYNC_ATTR_TIMEREF_OFFSET_NS",
        "short_name": "OFFSET_NS",
        "long_name": "NISYNC_ATTR_TIMEREF_OFFSET_NS",
        "namespace": "TimeReference",
        "type": "ViReal64",
        "visibility": "public",
    },
    1150804: {
        "name": "TIME_REFERENCE_CORRECTION",
        "full_name": "NISYNC_ATTR_TIMEREF_CORRECTION",
        "short_name": "CORRECTION",
        "long_name": "NISYNC_ATTR_TIMEREF_CORRECTION",
        "namespace": "Session",
        "type": "ViReal64",
        "visibility": "public",
    },
    1150805: {
        "name": "TIME_REFERENCE_UTC_OFFSET",
        "full_name": "NISYNC_ATTR_TIMEREF_UTC_OFFSET",
        "short_name": "UTC_OFFSET",
        "long_name": "NISYNC_ATTR_TIMEREF_UTC_OFFSET",
        "namespace": "TimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150806: {
        "name": "TIME_REFERENCE_UTC_OFFSET_VALID",
        "full_name": "NISYNC_ATTR_TIMEREF_UTC_OFFSET_VALID",
        "short_name": "UTC_OFFSET_VALID",
        "long_name": "NISYNC_ATTR_TIMEREF_UTC_OFFSET_VALID",
        "namespace": "TimeReference",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150807: {
        "name": "TIME_REFERENCE_LAST_SYNC_ID",
        "full_name": "NISYNC_ATTR_TIMEREF_LAST_SYNC_ID",
        "short_name": "LAST_SYNC_ID",
        "long_name": "NISYNC_ATTR_TIMEREF_LAST_SYNC_ID",
        "namespace": "TimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150809: {
        "name": "TIME_REFERENCE_SELECTED_TYPE",
        "full_name": "NISYNC_ATTR_TIMEREF_SELECTED_TYPE",
        "short_name": "SELECTED_TYPE",
        "long_name": "NISYNC_ATTR_TIMEREF_SELECTED_TYPE",
        "namespace": "Session",
        "type": "ViString",
        "visibility": "public",
    },
    1150810: {
        "name": "TIME_REFERENCE_TYPE",
        "full_name": "NISYNC_ATTR_TIMEREF_TYPE",
        "short_name": "TYPE",
        "long_name": "NISYNC_ATTR_TIMEREF_TYPE",
        "namespace": "TimeReference",
        "type": "ViString",
        "visibility": "public",
    },
    1150811: {
        "name": "TIME_REFERENCE_SELECTED_NAME",
        "full_name": "NISYNC_ATTR_TIMEREF_SELECTED_NAME",
        "short_name": "SELECTED_NAME",
        "long_name": "NISYNC_ATTR_TIMEREF_SELECTED_NAME",
        "namespace": "Session",
        "type": "ViString",
        "visibility": "public",
    },
    1150812: {
        "name": "TIME_REFERENCE_ENABLED",
        "full_name": "NISYNC_ATTR_TIMEREF_ENABLED",
        "short_name": "ENABLED",
        "long_name": "NISYNC_ATTR_TIMEREF_ENABLED",
        "namespace": "TimeReference",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150813: {
        "name": "TIME_REFERENCE_IS_SELECTED",
        "full_name": "NISYNC_ATTR_TIMEREF_IS_SELECTED",
        "short_name": "IS_SELECTED",
        "long_name": "NISYNC_ATTR_TIMEREF_IS_SELECTED",
        "namespace": "TimeReference",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150900: {
        "name": "GPS_ANTENNA_CONNECTED",
        "full_name": "NISYNC_ATTR_GPS_ANTENNA_CONNECTED",
        "short_name": "ANTENNA_CONNECTED",
        "long_name": "NISYNC_ATTR_GPS_ANTENNA_CONNECTED",
        "namespace": "GPSTimeReference",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150901: {
        "name": "GPS_RECALCULATE_POSITION",
        "full_name": "NISYNC_ATTR_GPS_RECALCULATE_POSITION",
        "short_name": "RECALCULATE_POSITION",
        "long_name": "NISYNC_ATTR_GPS_RECALCULATE_POSITION",
        "namespace": "GPSTimeReference",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150902: {
        "name": "GPS_SATELLITES_AVAILABLE",
        "full_name": "NISYNC_ATTR_GPS_SATELLITES_AVAILABLE",
        "short_name": "SATELLITES_AVAILABLE",
        "long_name": "NISYNC_ATTR_GPS_SATELLITES_AVAILABLE",
        "namespace": "GPSTimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150903: {
        "name": "GPS_SELF_SURVEY",
        "full_name": "NISYNC_ATTR_GPS_SELF_SURVEY",
        "short_name": "SELF_SURVEY",
        "long_name": "NISYNC_ATTR_GPS_SELF_SURVEY",
        "namespace": "GPSTimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150904: {
        "name": "GPS_MOBILE_MODE",
        "full_name": "NISYNC_ATTR_GPS_MOBILE_MODE",
        "short_name": "MOBILE_MODE",
        "long_name": "NISYNC_ATTR_GPS_MOBILE_MODE",
        "namespace": "GPSTimeReference",
        "type": "ViBoolean",
        "visibility": "public",
    },
    1150905: {
        "name": "GPS_STATUS",
        "full_name": "NISYNC_ATTR_GPS_STATUS",
        "short_name": "STATUS",
        "long_name": "NISYNC_ATTR_GPS_STATUS",
        "namespace": "GPSTimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1150801: {
        "name": "TIME_REFERENCE_CURRENT",
        "full_name": "NISYNC_ATTR_TIMEREF_CURRENT",
        "short_name": "CURRENT",
        "long_name": "NISYNC_ATTR_TIMEREF_CURRENT",
        "namespace": "TimeReference",
        "visibility": "public",
    },
    1150803: {
        "name": "TIME_REFERENCE_CLK_ADJ_OFFSET",
        "full_name": "NISYNC_ATTR_TIMEREF_CLK_ADJ_OFFSET",
        "short_name": "CLK_ADJ_OFFSET",
        "long_name": "NISYNC_ATTR_TIMEREF_CLK_ADJ_OFFSET",
        "namespace": "_Deprecated",
        "visibility": "public",
    },
    1150906: {
        "name": "GPS_UTC_OFFSET",
        "full_name": "NISYNC_ATTR_GPS_UTC_OFFSET",
        "short_name": "UTC_OFFSET",
        "long_name": "NISYNC_ATTR_GPS_UTC_OFFSET",
        "namespace": "_Deprecated",
        "visibility": "public",
    },
    1151000: {
        "name": "IRIG_TAI_OFFSET",
        "full_name": "NISYNC_ATTR_IRIG_TAI_OFFSET",
        "short_name": "TAI_OFFSET",
        "long_name": "NISYNC_ATTR_IRIG_TAI_OFFSET",
        "namespace": "_Deprecated",
        "visibility": "public",
    },
    1151100: {
        "name": "IEEE_8021AS_PORT_STATE",
        "full_name": "NISYNC_ATTR_8021AS_PORT_STATE",
        "short_name": "PORT_STATE",
        "long_name": "NISYNC_ATTR_8021AS_PORT_STATE",
        "namespace": "IEEE8021ASPort",
        "type": "ViInt32",
        "visibility": "public",
    },
    1151101: {
        "name": "IEEE_8021AS_CLOCK_ID",
        "full_name": "NISYNC_ATTR_8021AS_CLOCK_ID",
        "short_name": "CLOCK_ID",
        "long_name": "NISYNC_ATTR_8021AS_CLOCK_ID",
        "namespace": "IEEE8021ASTimeReference",
        "type": "ViString",
        "visibility": "public",
    },
    1151102: {
        "name": "IEEE_8021AS_CLOCK_CLASS",
        "full_name": "NISYNC_ATTR_8021AS_CLOCK_CLASS",
        "short_name": "CLOCK_CLASS",
        "long_name": "NISYNC_ATTR_8021AS_CLOCK_CLASS",
        "namespace": "IEEE8021ASTimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1151103: {
        "name": "IEEE_8021AS_CLOCK_ACCURACY",
        "full_name": "NISYNC_ATTR_8021AS_CLOCK_ACCURACY",
        "short_name": "CLOCK_ACCURACY",
        "long_name": "NISYNC_ATTR_8021AS_CLOCK_ACCURACY",
        "namespace": "IEEE8021ASTimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1151104: {
        "name": "IEEE_8021AS_PRIORITY1",
        "full_name": "NISYNC_ATTR_8021AS_PRIORITY1",
        "short_name": "PRIORITY1",
        "long_name": "NISYNC_ATTR_8021AS_PRIORITY1",
        "namespace": "IEEE8021ASTimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1151105: {
        "name": "IEEE_8021AS_PRIORITY2",
        "full_name": "NISYNC_ATTR_8021AS_PRIORITY2",
        "short_name": "PRIORITY2",
        "long_name": "NISYNC_ATTR_8021AS_PRIORITY2",
        "namespace": "IEEE8021ASTimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1151106: {
        "name": "IEEE_8021AS_GRANDMASTER_CLOCK_ID",
        "full_name": "NISYNC_ATTR_8021AS_GRANDMASTER_CLOCK_ID",
        "short_name": "GRANDMASTER_CLOCK_ID",
        "long_name": "NISYNC_ATTR_8021AS_GRANDMASTER_CLOCK_ID",
        "namespace": "IEEE8021ASTimeReference",
        "type": "ViString",
        "visibility": "public",
    },
    1151107: {
        "name": "IEEE_8021AS_GRANDMASTER_CLOCK_CLASS",
        "full_name": "NISYNC_ATTR_8021AS_GRANDMASTER_CLOCK_CLASS",
        "short_name": "GRANDMASTER_CLOCK_CLASS",
        "long_name": "NISYNC_ATTR_8021AS_GRANDMASTER_CLOCK_CLASS",
        "namespace": "IEEE8021ASTimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1151108: {
        "name": "IEEE_8021AS_GRANDMASTER_CLOCK_ACCURACY",
        "full_name": "NISYNC_ATTR_8021AS_GRANDMASTER_CLOCK_ACCURACY",
        "short_name": "GRANDMASTER_CLOCK_ACCURACY",
        "long_name": "NISYNC_ATTR_8021AS_GRANDMASTER_CLOCK_ACCURACY",
        "namespace": "IEEE8021ASTimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1151109: {
        "name": "IEEE_8021AS_GRANDMASTER_PRIORITY1",
        "full_name": "NISYNC_ATTR_8021AS_GRANDMASTER_PRIORITY1",
        "short_name": "GRANDMASTER_PRIORITY1",
        "long_name": "NISYNC_ATTR_8021AS_GRANDMASTER_PRIORITY1",
        "namespace": "IEEE8021ASTimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1151110: {
        "name": "IEEE_8021AS_GRANDMASTER_PRIORITY2",
        "full_name": "NISYNC_ATTR_8021AS_GRANDMASTER_PRIORITY2",
        "short_name": "GRANDMASTER_PRIORITY2",
        "long_name": "NISYNC_ATTR_8021AS_GRANDMASTER_PRIORITY2",
        "namespace": "IEEE8021ASTimeReference",
        "type": "ViInt32",
        "visibility": "public",
    },
    1151111: {
        "name": "IEEE_8021AS_LOG_SYNC_INTERVAL",
        "full_name": "NISYNC_ATTR_8021AS_LOG_SYNC_INTERVAL",
        "short_name": "LOG_SYNC_INTERVAL",
        "long_name": "NISYNC_ATTR_8021AS_LOG_SYNC_INTERVAL",
        "namespace": "IEEE8021ASPort",
        "type": "ViInt32",
        "visibility": "public",
    },
    1151112: {
        "name": "IEEE_8021AS_LOG_ANNOUNCE_INTERVAL",
        "full_name": "NISYNC_ATTR_8021AS_LOG_ANNOUNCE_INTERVAL",
        "short_name": "LOG_ANNOUNCE_INTERVAL",
        "long_name": "NISYNC_ATTR_8021AS_LOG_ANNOUNCE_INTERVAL",
        "namespace": "IEEE8021ASPort",
        "type": "ViInt32",
        "visibility": "public",
    },
    1151113: {
        "name": "IEEE_8021AS_INTERFACE_NAME",
        "full_name": "NISYNC_ATTR_8021AS_INTERFACE_NAME",
        "short_name": "INTERFACE_NAME",
        "long_name": "NISYNC_ATTR_8021AS_INTERFACE_NAME",
        "namespace": "IEEE8021ASPort",
        "type": "ViString",
        "visibility": "public",
    },
    1151114: {
        "name": "IEEE_8021AS_NEIGHBOR_PROP_DELAY_THRESH",
        "full_name": "NISYNC_ATTR_8021AS_NEIGHBOR_PROP_DELAY_THRESH",
        "short_name": "NEIGHBOR_PROP_DELAY_THRESH",
        "long_name": "NISYNC_ATTR_8021AS_NEIGHBOR_PROP_DELAY_THRESH",
        "namespace": "IEEE8021ASPort",
        "type": "ViInt32",
        "visibility": "public",
    },
    1151115: {
        "name": "IEEE_8021AS_AS_CAPABLE",
        "full_name": "NISYNC_ATTR_8021AS_AS_CAPABLE",
        "short_name": "AS_CAPABLE",
        "long_name": "NISYNC_ATTR_8021AS_AS_CAPABLE",
        "namespace": "IEEE8021ASPort",
        "type": "ViBoolean",
        "visibility": "public",
    },
}
